### ISSUE TITLE
Enemies dont despawn

### ISSUE THREAD

**Issue by Phuple** [Memori-Studios/CastlesOnClouds-Playtest#10]
Current Behavior:
At a certain point in a run, enemies will die, their models will not despawn but they will still move to the objective in their dead state (laying on the ground as if they are about to despawn), sometimes units/buildings can lock onto these entities.

Expected Behavior
The entities should despawn

Steps To Reproduce
Unsure, I just played the game normally, it seems to only happen after a certain amount of waves (unaware of how many).

Playtest Version (top left corner)
v4.2.1

Environment Specs

OS: Windows 10

- GPU: Nvidia GTX 1060 Gaming X 6GB
- CPU: i5 - 9400F
- RAM: 8 Gigs

Anything else?
No

**Comment by Memori-Studios** [comment]
old bug resolved in the combat overhaul of 4.4.0, if anything appears again Ill reopen it
