### ISSUE TITLE
Esc to get back from metaprogression screen

### ISSUE THREAD

**Issue by curiouspers** [Memori-Studios/CastlesOnClouds-Playtest#101]
### Description

Esc to get back from metaprogression screen please

**Comment by Memori-Studios** [comment]
Added in 0.0.4 Great Idea thanks

**Comment by curiouspers** [comment]
Thanks! I'd expect Esc to work the same way for Unlocks, Upgrades, Encyclopedia, Settings, Leaderboards menu.

**Comment by Memori-Studios** [comment]
totally fair, will add when I have time
