### ISSUE TITLE
Max framerate setting has no effect

### ISSUE THREAD

**Issue by curiouspers** [Memori-Studios/CastlesOnClouds-Playtest#102]
### Current Behavior

Max framerate setting has no effect
![image](https://github.com/user-attachments/assets/3d143002-925f-4da8-bc74-46c9990725da)

### Expected Behavior

Should set it to value that label says

### Steps To Reproduce

Open settings
See 170fps, 
Click Max Frame Rate, select 50hz
Click Apply
See it has no effect
Vsync on/off does not matter

### Playtest Version (center top)

v0.0.3

### Seed (copy button center top)

Seed: 111012-2602

### Environment Specs

- OS:  Windows 11
- GPU: Nvidia RTX 3080
- CPU: i9 14900
- RAM: 64 Gigs

### Anything else?

Great videos, seen them all, wish you all the best with this release!

**Comment by Memori-Studios** [comment]
Fixed it in 0.0.5, yes it wasnt applying. Also make sure that vsync is not checked as that overrides it
![image](https://github.com/user-attachments/assets/60de93db-fbfc-4aac-ab4f-b1709422b484)
https://store.steampowered.com/news/app/1668620/view/4610084577353469502
