### ISSUE TITLE
Game doesn't run after completing a season

### ISSUE THREAD

**Issue by Sloddervos66** [Memori-Studios/CastlesOnClouds-Playtest#103]
### Current Behavior

When I die during the second season and I try playing another game afterwards, the game does not let me start the wave nor does it let me place towers or move my hero.

### Expected Behavior

The game should allow me to place towers, move my hero and start the wave.

### Steps To Reproduce

1. From a fresh save, play through the first full season.
2. Try to get 2 points (don't know exactly if this is relevant)
3. Spend your points in the metaprogression on: silvershade outpost and the pointy-est of arrows (again not sure if required, but just letting know what I did)
4. Start a new game and from there the game does not run for me

### Playtest Version (center top)

v0.0.3

### Seed (copy button center top)

111012-6973

### Environment Specs

- OS: Windows 11
- GPU: Intel Iris XE
- CPU: i5
- RAM: 16 gb

**Comment by Sloddervos66** [comment]
Here's the player.log file. I opened the game and tried starting a new run getting that same bug I had before. I hope it's enough, if not. I'll reproduce my steps completely again.
[Player.log](https://github.com/user-attachments/files/16786592/Player.log)

**Comment by Memori-Studios** [comment]
Dude thank you so much! I see the error is with a card with a broken id, can you send me the saveData.json file as well

**Comment by Sloddervos66** [comment]
Of course! Here's the saveData.json.
[saveData.json](https://github.com/user-attachments/files/16786862/saveData.json)

**Comment by Memori-Studios** [comment]
Fixed! Thank you so much for your help! If you update to the latest version of the game you should be good to go, any further issues feel free to reopen this or create a new one. 

[0.0.4 Bug Fixes - new player.log fetcher](https://store.steampowered.com/news/app/1668620/view/4610084577350727653)

**Comment by Sloddervos66** [comment]
Nice! This fix indeed worked and it automatically fixed another bug where abandoning a run would crash the game, now I can actually progress!

**Comment by Memori-Studios** [comment]
Awesome, I appreciate your patience. This is my first release but with the savedata and player log files I should be able to triage bugs much more rapidly going forward
