### ISSUE TITLE
Enemies all stuck around castle, new game can't select towers to place

### ISSUE THREAD

**Issue by Broudy001** [Memori-Studios/CastlesOnClouds-Playtest#104]
### Current Behavior

Was playing through a save, and the map in Autumn the enemies all just stopped at the entrance to the castle, circled around the entrance till I eventually was able to kill them all.  Couldn't click on the hero either to move him

Tried starting a new game, but when I got into the map, all the towers were showing as unselectable.  Had 500 gold available

Also wasn't getting the choice of cards at the end of each wave either

https://github.com/user-attachments/assets/6e8ed6a0-062b-4da7-b4d1-163948c12bc8

### Expected Behavior

I should have had my castle sacked many times over

### Steps To Reproduce

Honestly I'm not sure how I got to this point.  I was initially playing through Parsec, 

### Playtest Version (center top)

v0.0.03

### Seed (copy button center top)

Seed: 111012-8943

### Environment Specs

- OS: Windows 11
- GPU: TRX 4080
- CPU: i7
- RAM: 64GB

**Comment by Memori-Studios** [comment]
Thanks for the detailed write up, currently investigating. Today I added a button that links to the Player.log file, if you encounter the issue again can you upload that file for me? Thanks
![image](https://github.com/user-attachments/assets/6c30c98e-a0c2-49c9-b411-bea00aad4c84)

**Comment by Memori-Studios** [comment]
The issue with non of the towers selectable should be corrected in 0.0.5. If bug occurs in the future feel free to reopen
