### ISSUE TITLE
cant build any building

### ISSUE THREAD

**Issue by MildlyWarmToast** [Memori-Studios/CastlesOnClouds-Playtest#105]
### Current Behavior

every single building even the starter ones are not interactable saying I am missing the required building to place them. This includes stuff like the farm melee and archer tower which have no prerequisite. additionally I cannot start the wave and both the button and icon are missing

### Expected Behavior

well it should probably work as usual

### Steps To Reproduce

happen after I started a new game while already having an ongoing save

### Playtest Version (center top)

v0.0.4

### Seed (copy button center top)

Seed: 111012-2285

### Environment Specs

- OS: windows 11
- GPU: nvidia gtx 1650
- CPU: amd ryzen 7 5800hs
- RAM: 16 gb

### Anything else?

nah

**Comment by Memori-Studios** [comment]
Pushed a new build about 30 seconds ago that fixed a major issue, can you give it a shot now?

https://store.steampowered.com/news/app/1668620/view/4610084577350727653

**Comment by MildlyWarmToast** [comment]
sorry for the late response. the patch seems to have fixed it. Thanks!
