### ISSUE TITLE
Same controls on upgrades(meta-progression) page

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#106]
### Description

ability to move around the abilities with the right mouse drag, similar to the ability in the game.  I know this is a overly knit picky thing, but just makes my lazy life easier to use the mouse for everything.

**Comment by Memori-Studios** [comment]
Added in 0.0.6 Nothing wrong with being picky if it takes 15 minutes to add haha

https://store.steampowered.com/news/app/1668620/view/4610084577357037789
