### ISSUE TITLE
Spell Cooldown bugged

### ISSUE THREAD

**Issue by Bafffe** [Memori-Studios/CastlesOnClouds-Playtest#109]
### Current Behavior

After i got the spell cooldwon down to 15% via cards, placing the church witch should halve it added 50% so it was 65% again, after selling it it was back to 15%

### Expected Behavior

it should either halve the cooldown or let there be a minimum, but it should not add 50%

### Steps To Reproduce

Get cards to get cooldown to 15% then place the church

### Playtest Version (top left)

v0.0.5

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
Fixed in 0.0.6, Thanks for reporting!

https://store.steampowered.com/news/app/1668620/view/4610084577357037789
