### ISSUE TITLE
Menu UI bug after loss

### ISSUE THREAD

**Issue by SuperMrCart** [Memori-Studios/CastlesOnClouds-Playtest#110]
### Current Behavior

Unable to click any menu ui on the left side elements except for the ones that link you to an external page.
So Play, Unlocks,Upgrades,Encyclopedia,Settings,Leaderboards, and Quit do not function after a loss you'll have to altf4 to start again.

### Expected Behavior

It should allow you to move between the menus.

### Steps To Reproduce

Start a match with all the default settings, let the mobs win the first round or just lose over time whichever, spam left-click to click past the last UI, and break the menus. clicking the left mouse button after finishing a game, seems to do it 

### Playtest Version (top left)

v0.0.6

### Seed (copy button top left)

111012-7434

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
Fixed in 0.0.7, thanks for info on spamming the button lol

https://store.steampowered.com/news/app/1668620/view/4610084577360978632
