### ISSUE TITLE
Might over magic small mistake

### ISSUE THREAD

**Issue by Bafffe** [Memori-Studios/CastlesOnClouds-Playtest#112]
### Current Behavior

Might over magic should decreases the costs of archers, melee and artillery by 25% and increases the cooldown of spells by 20% but instead it is written that it should only reduce the cost by 15%

### Expected Behavior

either decrease the cost by 15% or text change to 25% reduction

### Steps To Reproduce

look at the card Might over magic, you see it says -15% but at the bottom of the card it shows -25%

### Playtest Version (top left)

v0.0.6

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
Fixed in 0.1.1 Thanks
