### ISSUE TITLE
Crash After Upgrades

### ISSUE THREAD

**Issue by tsargent92** [Memori-Studios/CastlesOnClouds-Playtest#113]
### Current Behavior

First off, awesome game. I love the visual assets too. Is it Synty? Okay, to the bug I found. Upon hitting PLAY, my UI disappeared as expected, but my island kept spinning with nothing further. I couldn't hit escape. I had to CTL-ALT-DEL out of it.

### Expected Behavior

Upgrade, hit play, UI disappear, go directly into gameplay.

### Steps To Reproduce

I had played a few runs in a row and leveled up. When I was in the menu, I upgraded "Abbreviated Incantations, Tele 360 No Scope, Deutschland Engineering, and The Pointy-est Of Arrows", I then went back to the main menu and hit play.

### Playtest Version (top left)

v0.0.6

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Please Attach Player.Log and saveData.json files here

[Player.log](https://github.com/user-attachments/files/16825109/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16825110/Player-prev.log)

### Anything else?

Like I said above, AWESOME game and concept. Keep it up!

**Comment by Memori-Studios** [comment]
Thanks for the detailed Steps To Reproduce! I checked out your logs and Im pretty sure the issue was fixed in 0.0.7. Thanks for the feedback and if you ever see the issue again feel free to reopen this ticket
