### ISSUE TITLE
Freeze on starting Winter Season after resumed from save

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#114]
### Current Behavior

Not allowed to plaec any buildings or interact with ready from the screen before starting winter

### Expected Behavior

can interact with buttons

### Steps To Reproduce

Play first season, and complete level, save game and exit, return to play autumn season and complete autumn season to be stuck at winter season, was able to continue after exiting and allowing to save and then returning back to save from main menu

### Playtest Version (top left)

v0.0.7

### Seed (copy button top left)

111012-939611

### Environment Specs

- OS: Win 11
- GPU: Nvidia RTX 3060
- CPU: AMD
- RAM: 32 gb

### Please Attach Player.Log and saveData.json files here

[saveData.json](https://github.com/user-attachments/files/16825732/saveData.json)
[Player.log](https://github.com/user-attachments/files/16825733/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16825734/Player-prev.log)

**Comment by Memori-Studios** [comment]
fixed in 0.1.2 thanks
