### ISSUE TITLE
Stuck on next season

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#116]
### Current Behavior

When finishing a season and going to the next, can't click ready button

### Expected Behavior

Able to click ready button to start the next season

### Steps To Reproduce

1. Play full game on max speed
2. Proceed to next season
3. Cant click ready

### Playtest Version (top left)

V0.1.0

### Seed (copy button top left)

Seed: 111012-42951

### Environment Specs

OS: Windows 10
GPU: RX 7700
CPU: i7-10700F
RAM: 32 GB

### Please Attach Player.Log and saveData.json files here

[Player.log](https://github.com/user-attachments/files/16831127/Player.log)
[saveData.json](https://github.com/user-attachments/files/16831128/saveData.json)

### Anything else?

Going back to main menu and continue the save works

**Comment by Memori-Studios** [comment]
fixed in 0.1.2 thanks
