### ISSUE TITLE
Not gaining gold correctly, perhaps?

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#117]
### Current Behavior

Not accruing gold correctly, when i drop a werewolf im not recieving any gold.

### Expected Behavior

I would expect more money when taking down a werewolf or larger enemy

### Steps To Reproduce

Playing autumn season

### Playtest Version (top left)

0.1.2

### Seed (copy button top left)

111012-73421

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Please Attach Player.Log and saveData.json files here

[Player.log](https://github.com/user-attachments/files/16842763/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16842764/Player-prev.log)
[saveData.json](https://github.com/user-attachments/files/16842765/saveData.json)

### Anything else?

Tried to attach a video of the game play but was to large, is there somewhere i could send this directly?

**Comment by Memori-Studios** [comment]
fixed in 0.1.4, I broke it when I was fixing some of the relic bugs. Should be all good now thanks for reporting
