### ISSUE TITLE
Game freezes upon completing season 1

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#118]
### Current Behavior

When completing Sprint of Year one, goes to a black screen

### Expected Behavior

Move on to Year 2

### Steps To Reproduce

Complete Sprint year 1

### Playtest Version (top left)

0.1.4

### Seed (copy button top left)

111012-82301111

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
Does this still occur?

**Comment by dsabella84** [comment]
still occurs, i finish the spring on year 1 and the screen just goes to black like its stuck in a transition screen

**Comment by dsabella84** [comment]
[saveData.json](https://github.com/user-attachments/files/16996961/saveData.json)
[Player.log](https://github.com/user-attachments/files/16996963/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16996964/Player-prev.log)

**Comment by Memori-Studios** [comment]
Ah sorry wasn't understanding the issue. I have added a game over screen in 0.3.0 And you should now see that sovereign reign mode is unlocked. Thanks as always for your reports!
