### ISSUE TITLE
Weird format on card

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#119]
### Current Behavior

im assuming that the gold drop rate should be a whole number rather than a percent

### Expected Behavior

whole number on drop rate

### Steps To Reproduce

start of season where gold drop rate has been adjusted by 2 other cards prior and attempting to increase with the Quantitative Easing

![image](https://github.com/user-attachments/assets/4220e981-9304-4875-8cd6-9d39c0b2abd9)

![image](https://github.com/user-attachments/assets/b4a593c7-757b-416f-9e10-6fcc0dbdb7b4)

![image](https://github.com/user-attachments/assets/2c4022be-dd28-47cc-8b26-46b7fdcb4078)

![image](https://github.com/user-attachments/assets/5da481fd-a160-4f47-ab54-93d4b5d03148)

![image](https://github.com/user-attachments/assets/c8f291cd-b797-4610-883a-3fb8f18fe097)

### Playtest Version (top left)

0.2.2

### Seed (copy button top left)

111012-8230111

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Please Attach Player.Log and saveData.json files here

[saveData.json](https://github.com/user-attachments/files/16931947/saveData.json)
[Player.log](https://github.com/user-attachments/files/16931950/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16931951/Player-prev.log)

**Comment by Memori-Studios** [comment]
You are correct in your assumption, fixed in 0.2.3. Thanks as always man
