### ISSUE TITLE
Dead bodies after final wave

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#12]
Current Behavior

When I beat the last wave dead bodies of goblins keep going to castle. They don't get attacked and don't do any damage to castle.

Expected Behavior

Dead bodies should disappear.

Steps To Reproduce

Beat wave 22.

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/422e50ff-36eb-45dc-b0d6-8c8fac7f6fff)

Playtest Version (top left corner)

v4.2.2

Environment Specs

OS: Arch Linux GPU: Nvidia RTX 3070 CPU: Ryzen 5600X RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 4.4.0 with new seasons format
