### ISSUE TITLE
Start New Game Modal

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#120]
### Current Behavior

Currently when you hover over the cancel button it expands and covers up the red X,  Not sure if that red X should be there but the overlay of the text on hover makes for a weird ui

### Expected Behavior

either remove the red x or push teh button to be larger perhaps

### Steps To Reproduce

Start new Game:
![image](https://github.com/user-attachments/assets/a97e6769-eb63-4fd6-8e52-7243c64dd485)

![image](https://github.com/user-attachments/assets/af169440-fb85-47a6-ae9f-3496f248dc5b)

### Playtest Version (top left)

0.2.3

### Seed (copy button top left)

111012-5629

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
yeah looks sloppy, resolved in 0.2.4
