### ISSUE TITLE
Spawning of enemies stopped

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#121]
### Current Behavior

Player Autumn Year 1 and on wave 10 no enemies came out now its stuck on Wave 11, happened again but this time in winter, Wave 5 no enemies and moved to wave 6 no enemies and stuck.  Ok it actually doesnt get stuck but continues each wave with no enemies appearing and i was able to get through all seasons with out battling anyone.

### Expected Behavior

more enemies for each wave

### Steps To Reproduce

not to sure

### Playtest Version (top left)

0.3.0

### Seed (copy button top left)

111012-6961

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Please Attach Player.Log and saveData.json files here

[Player.log](https://github.com/user-attachments/files/17003195/Player.log)
[saveData.json](https://github.com/user-attachments/files/17003196/saveData.json)
[Player-prev.log](https://github.com/user-attachments/files/17003197/Player-prev.log)

**Comment by Memori-Studios** [comment]
Quick question, were you playing on a save that already existed before the 0.3.0 update?

**Comment by Memori-Studios** [comment]
Actually might have figured it out looking through the logs, looks like the relic that decreases the frequency of the merchant showing up was breaking if he doesnt show up for a really long time. That is called when the wave spawns leading to the spawning breaking. Fixed in 0.3.1
