### ISSUE TITLE
Unknown Relic

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#122]
### Current Behavior

When i hover over a relic it should provide a description of that relic, looks like bad relics were added, side behviour, i purchased the merchant relic to increase his appearance with 10 % incrase, but he actually has not shown up more

![image](https://github.com/user-attachments/assets/6e24a13a-218f-469d-b1b0-6861b0613cb4)

### Expected Behavior

description of relic should be shown

### Steps To Reproduce

cant remember all the relics i purchased so unfortunately not

### Playtest Version (top left)

0.3.0

### Seed (copy button top left)

111012-6961

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Please Attach Player.Log and saveData.json files here

[Player.log](https://github.com/user-attachments/files/17003215/Player.log)
[saveData.json](https://github.com/user-attachments/files/17003216/saveData.json)

**Comment by Memori-Studios** [comment]
Oh sick this was actually fixed in 0.3.1 It was due to applying merchant shop prices modifications from the relic before the shop was loaded, breaking the whole process.
