### ISSUE TITLE
Relics wrap behind the king gui

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#123]
### Current Behavior

Cant see all relics purchased from the bottom left, hidden behind king Leroy;s GUI

![image](https://github.com/user-attachments/assets/4d1c6552-4341-4237-8c56-b6e19344b024)

### Expected Behavior

Ability to see all relics

### Steps To Reproduce

purchase more than 7 relics

### Playtest Version (top left)

0.3.0

### Seed (copy button top left)

111012-6961

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Please Attach Player.Log and saveData.json files here

[Player.log](https://github.com/user-attachments/files/17003221/Player.log)
[saveData.json](https://github.com/user-attachments/files/17003222/saveData.json)

**Comment by Memori-Studios** [comment]
fixed in v0.3.2 also added a little button to show or hide
![image](https://github.com/user-attachments/assets/1a55ac32-367a-4426-8fe0-2d758d9f75fd)
