### ISSUE TITLE
Can upgrade cards beyond max level

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#13]
Current Behavior

Upgrade cards appear even after they are maxed out.

Expected Behavior

I should not be able to get an option to upgrade stuff I've already maxed out.

Steps To Reproduce

- Upgrade card to its max level.
- Get lucky when upgrading to get the card.

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/7446c38d-17f9-4b56-a826-06b187c1be59)

Playtest Version (top left corner)

v4.2.2

Environment Specs

OS: Arch Linux GPU: Nvidia RTX 3070 CPU: Ryzen 5600X RAM: 32 GB

Anything else?

As you can see I'm also able to upgrade 'Scholar's guild' from level 4 to 5 even though I've already maxed it out on previous level upgrade. These two might be related.

**Comment by Phuple** [comment]
Can confirm, this bug also happens to me

**Comment by Micovec** [comment]
Fixed in 4.2.3
