### ISSUE TITLE
Structures do not clean trees

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#14]
Current Behavior

Structures do not clean trees when placed in forest.

Expected Behavior

Trees that are inside placed structures should disappear.

Steps To Reproduce

Place structure in forest.

Playtest Version (top left corner)

v4.2.2

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/98005357/a4d36f37-baad-4928-91a4-9de23afb6008)
The towers clear them on points, is this not what you are experiencing?

**Comment by Micovec** [comment]
Yes, towers don't clear trees for me

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/03013840-f4a9-4316-ad65-d991f44c0989)

**Comment by Micovec** [comment]
Fixed in 4.2.3
