### ISSUE TITLE
Clouds get in the way

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#15]
Current Behavior

Clouds get in the way when looking at the island from a height.

Suggested Behavior

Hide all clouds above island or make them transparent when looking through them at the island

Playtest Version (top left corner)

v4.2.2

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.3.0, camera now hides all clouds if you go above a y threshold :(
