### ISSUE TITLE
Structure build menu sometimes does not close

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#17]
Current Behavior

Structure build menu sometimes does not close when I open it and then click somewhere on the island.

Expected Behavior

Not sure what the expected behavior is but it should be consistent. Either don't close the menu or close it every time when I click on a tile or somewhere else.

Steps To Reproduce

- Open build menu
- Click somewhere on the island, menu closes
- Open build menu again
- Click somewhere on the island, menu does not close

Playtest Version (top left corner)

v4.2.2

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Micovec** [comment]
Just tested this in 4.2.3. Now it seems like the menu closes on a second click anywhere on the island. But if you keep repeating the cycle of opening build menu and clicking somewhere on the island eventually the menu won't close.

**Comment by Memori-Studios** [comment]
Replicated and resolved in 4.4.1. Actual spaghetti code caused this
