### ISSUE TITLE
Tooltips don't have slide animation when shown consecutively

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#18]
Current Behavior

Tooltips don't have slide animation when shown consecutively, on the same UI element.

Expected Behavior

Expected animation.

Steps To Reproduce

- Hover mouse over a UI element that does have tooltip, tooltip shows with slide animation
- Move mouse away from element but not on another element with tooltip
- Hover mouse over the UI element again, there's no slide animation

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.3.0 thanks
