### ISSUE TITLE
Can select multiple powers

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#19]
Current Behavior

I can select multiple powers while in-game but only the last one is actually selected. UI tells me they are all selected.

Expected Behavior

When I select one power and then another one, the first should deselect.

Steps To Reproduce

- Click on power
- Click on another power, now both powers seem to be selected

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/40196734-b7c9-4ee2-94be-37aa232ac45c)

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Fixed in 4.3.0, ui now properly updates to deselect previously selected spell
