### ISSUE TITLE
[Bug] Overlapping and continuous generation

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#2]
**Current Behavior**
Overlapping and continuous generation. Disabling Randomize stops the generation

**Expected Behavior**
Generate once per Generate button click and remove previously generated island

**Steps To Reproduce**
1. Set all sliders to max (It seems like Paths and Rivers causes it)
2. Enable Randomize
3. Click Generate
4. Disable Randomize

Playtest 3.4.3

OS: Windows 10
GPU RX780 8 GB
CPU: i7-10700f
Ram: 32 GB

**Anything else?**
Video shows the continuous generation. Picture shows outcome

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/43e32aa1-3d29-48d1-a7ff-47f75a9ce166)

https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/83759a87-d317-4847-be39-ee207771e080

**Comment by Memori-Studios** [comment]
Fixed in version 3.4.4

Resolved by reducing thresholds for generation and preventing updating seed displayed when not randomizing
