### ISSUE TITLE
Artificer shoots beyond its range

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#20]
Current Behavior

Artificer seems to have a lock-on and keeps shooting enemies that go beyond its range.

Expected Behavior

Artificer should stop shooting at enemy that leaves its shooting range.

Steps To Reproduce

Best way to reproduce is to have an enemy with a lot of health enter artificer shooting range.

- Enemy enters artificer shooting range
- If the enemy is not killed in the range, artificer keeps shooting at it even though the enemy is long gone.
- Artificer keeps shooting at it until the enemy dies

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

Anything else?

The lock-on seems to occur even when placing artificer. I'm not sure how it decides on who to shoot but few times artificer shot a long range cannon ball when placed.

**Comment by Memori-Studios** [comment]
Fixed in 4.3.0, had some unique logic to fire differently on artillery towers after they play a little juice and that was screwing it up
