### ISSUE TITLE
Escape menu is behind upgrade cards

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#21]
Current Behavior

Escape menu is obstructed by level upgrades.

Expected Behavior

Escape menu should be on top of level upgrades.

Steps To Reproduce

- Wait until you get level upgrade
- Press escape

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.3.0. Did a major refactor of the camera pause and escape menu to now supersede everything (upgrades, shop, etc) so there maybe a bug or two I missed.
