### ISSUE TITLE
Can use powers multiple times before the first wave

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#22]
Current Behavior

I'm able to use powers before the first wave allowing me to spawn unlimited number of reinforcements.

Expected Behavior

Either:
- Allow me to use power once before the first wave
- Lock powers until the first wave comes

Steps To Reproduce

1. Generate new map
2. Use powers freely

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Actually think Im gonna leave this one in. Cooldowns will be a good bit longer in the future, just keeping them quick right now to allow players to test them out more and have fun. Reinforcements still despawn at the intended time so its all good
