### ISSUE TITLE
Helm of the Forest King increases range by 1000% instead of 10%

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#23]
Current Behavior

Helm of the Forest King increases range by 1000% instead of 10% as the description says.

Expected Behavior

Increase the range by 10%

Steps To Reproduce

Buy Helm of the Forest King from merchant.

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Fixed in 4.3.0 lol hope you enjoyed unlimited range
