### ISSUE TITLE
Castle health does not get updated when modified by relics

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#24]
Current Behavior

When a relic that modifies castle health gets bought health status in the top bar doesn't get updated. The same applies to health status at the shop.

However health status _is_ updated next time merchant comes by but only at the shop.

Expected Behavior

When relic that modifies castle health gets bought both health statuses should get updated. 

Steps To Reproduce

At the shop buy either one of:

- Forever gaunglet
- Myth thrill armor

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Fixed in 4.3.0, now correctly display ui update in both shop and main panel
