### ISSUE TITLE
Can build structures inside castle

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#25]
Current Behavior

I'm able to build structures inside castle.

Expected Behavior

I shouldn't be able to build any structures that collide with the castle.

Steps To Reproduce

1. Enter build mode
2. Select structure to build
3. Place it in castle

Playtest Version (top left corner)

v4.2.3

Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Fixed in 4.3.0 now blacklisting central point where keep is
