### ISSUE TITLE
Show increase amount in modifier cards rather than before & after.

### ISSUE THREAD

**Issue by viglucci** [Memori-Studios/CastlesOnClouds-Playtest#27]
### Description

When the player is selecting an upgrade for a stat, it might not be the most relevant to the player what the current value is. I would argue that it is most relevant howmuch the desired stat is going to increase by, and therefore that amount should be priortized in the text. Optionally you could retain the before / after by showing it at the end.

**Current:**
Increases some stat from 1.00 -> 1.01

**Proposed:**
Increases some stat by .01 (1.00 -> 1.01)

**Comment by Memori-Studios** [comment]
Added in 4.3.2 I like the change. not sure if I want to do percentages or fixed numbers, still deciding
