### ISSUE TITLE
Can build multiple institutions

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#29]
### Current Behavior

I'm able to build multiple institutions or collegiums when only one of each buildings are needed.

### Expected Behavior

I shouldn't be able to build more than on of institutions or collegiums.

### Steps To Reproduce

1. Build institution, now I can build artificer towers
2. Build more institutions

Same thing works for collegium and wizard towers

### Playtest Version (center top)

v4.3.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
nah, will leave in, might want to build a second one before you tear down your first to build something in its place
