### ISSUE TITLE
[Bug] Null Reference on new Enemy

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#3]
**Current Behavior**
Null Reference appears in the development console when reaching wave 4 and the new enemies appear

**Expected Behavior**
No null reference

**Steps To Reproduce**
1. Play the game
2. Reach the point where the new enemy appears

Playtest 3.4.3

OS: Windows 10
GPU RX780 8 GB
CPU: i7-10700f
Ram: 32 GB

**Anything else?**

Included [Player - Log.txt](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/files/13801222/Player.-.Log.txt) from the development console. From the logs it seems an Animator SetBoolString is the cause

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/f4e74109-ef3d-4be1-aa66-d6cbfd1e68fa)

**Comment by Memori-Studios** [comment]
Resolved in 3.4.4
