### ISSUE TITLE
Help screen is meant for older version

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#30]
### Current Behavior

Help screen is meant for older version than current 4.3.1

### Expected Behavior

Updated help screen

### Steps To Reproduce

1. Delete all game data
2. Start new game

### Playtest Version (center top)

v4.3.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Fixed in 4.3.2
