### ISSUE TITLE
Towers in build mode don't show their real range

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#31]
### Current Behavior

Towers don't show their real range in build mode. Range gets modified by upgrades or relics and those changes aren't present when placing towers.

### Expected Behavior

Towers should show their real range in build mode.

### Steps To Reproduce

1. Modify tower range by upgrades and/or relics
2. Enter build menu
3. Hover mouse over a location for towers
4. Only the base range is shown

### Playtest Version (center top)

v4.3.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Replicated and resolved in 4.4.1 thanks
