### ISSUE TITLE
Farms on hills are difficult to select

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#33]
### Current Behavior

It's very difficult to select farms that are on a hill. Those parts that are actually on a hill are impossible to select. The only way is to either select them by the edge or if section of them are on flat base terrain.

### Expected Behavior

I should be able to select them no matter if they are on a hill.

### Steps To Reproduce

1. Place farm on hill
2. Try to select them by spot that's actually on a hill

### Playtest Version (center top)

v4.3.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.3.2 Disabled building on Hills, its a feature now
