### ISSUE TITLE
Mystic collegium and Forge cannon institute structures don't have any tooltip

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#34]
### Current Behavior

Placed Mystic collegium and Forge cannon institute structures don't have any tooltip, like towers or houses do.

### Expected Behavior

Some kind of tooptip.

### Steps To Reproduce

1. Build either one of the two structures
2. Click on them

### Playtest Version (center top)

v4.3.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.3.2 thanks
