### ISSUE TITLE
Pressing escape in main menu opens escape menu in game

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#35]
### Current Behavior

When I press escape in main menu whether it's just in main menu, upgrade list or bestiary and start a game the escape menu pops up.

Escape menu also pops up in surrender screen.

### Expected Behavior

Escape menu should not open if I press escape in any other parts of the game just in play mode.

### Steps To Reproduce

1. Start game
2. Load to main menu
3. Press escape
4. Press Play
5. Press Start Game, escape menu pops up.

### Playtest Version (center top)

v4.3.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Replicated in 4.4.0, fixed in 4.4.1

**Comment by Micovec** [comment]
Cannot confirm it being fixed in 5.1.0
