### ISSUE TITLE
Tile Description UI 

### ISSUE THREAD

**Issue by SuperMrCart** [Memori-Studios/CastlesOnClouds-Playtest#36]
### Current Behavior

When clicking on the map you get a description of the tile type(grass or river or path)  this UI element bugs out when moving past it zoomed in it comes back into the view and doesn't leave until you zoom out.

### Expected Behavior

disappear it get out of view of the camera?

### Steps To Reproduce

click a spot on the map, zoom in and then w key past it.,

### Playtest Version (center top)

4.3.1

### Seed (copy button center top)

Seed: 111013-9401

### Environment Specs

- OS: [ Windows 10]
- GPU: [ Nvidia gtx 1060]
- CPU: [amd ryzen 5 6300]
- RAM: [. 16Gigs]

**Comment by Memori-Studios** [comment]
Replicated and Resolved in 4.4.1. Thanks Cart!
