### ISSUE TITLE
Tooltips not shown when game is paused

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#37]
### Current Behavior

Tooltips don't popup when game is paused with pause button.

### Expected Behavior

Tooltips should be shown even when game is paused.

### Steps To Reproduce

1. Play game
2. Pause game with pause button
3. Hover over any UI that has toolip

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 4.4.1 by switching to unscaled deltatime
