### ISSUE TITLE
Season reward tooltips are behind menu

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#38]
### Current Behavior

Season reward tooltips are behind pick menu making them hidden and not readable.

### Expected Behavior

Season reward tooltips should be on top of pick menu

### Steps To Reproduce

1. Finish season
2. Hover mouse over reward

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.4.1 , was due to a weird issue where the build loaded the scenes in a different order than the editor.
