### ISSUE TITLE
Magic towers cause others to have shooting animation even when they are not shooting

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#39]
### Current Behavior

Magic towers cause others to have shooting animation even when they are not shooting. From what I've seen this happens only to artillery and magic towers not archer towers.

### Expected Behavior

Towers should not have any animation when they aren't shooting.

### Steps To Reproduce

1. Place artillery tower
2. Place magic tower, artillery or magic towers now have shooting animation even when no enemy is in range

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Resolved in 4.4.1 Thanks this one was bothering me
