### ISSUE TITLE
Merchant medallian restocks merchant's relics

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#40]
### Current Behavior

Buying Merchant Medallian restocks merchant's relics that were bought in the same merchant visit.

### Expected Behavior

There shouldn't be any restocks when buying Merchant Medallian.

### Steps To Reproduce

1. Buy some relic/s
2. Buy Merchant Medallian in the same merchant visit, previously bought relics get restocked

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Replicated and resolved in 4.4.1
