### ISSUE TITLE
Typo in 'Shield of the Wanderer'

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#41]
### Current Behavior

Typo in 'Sheid of the Wanderer'

### Expected Behavior

Should be 'Shield of the Wanderer'. Sheild -> Shield

### Steps To Reproduce

1. Wait for merchant
2. Get Shield of the Wanderer

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
lol I cant spell sorry, fixed in 4.4.1
