### ISSUE TITLE
Units health bar is above menus

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#42]
### Current Behavior

Units health bar is above menus making it sometimes impossible to read information.

### Expected Behavior

Units health bar should be below other UI.

### Steps To Reproduce

1. Damage unit
2. Position any menu above unit's health bar (bottom menu for example)

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

### Anything else?

The only UI that is above health bar I've noticed is tooltips.

**Comment by Memori-Studios** [comment]
resolved in 4.4.1

**Comment by Micovec** [comment]
In 5.1.0 fixed partially: health bars are indeed behind bottom menu but are now on top of structure selecting menu.

**Comment by Memori-Studios** [comment]
thanks, added a custom rule to turn off healthbars for that one panel
