### ISSUE TITLE
Winter season ends on first boat arrival

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#43]
### Current Behavior

Winter season ends on first boat arrival, completely skipping season. I guess it's because there are missing waves?

### Expected Behavior

Waves in winter season.

### Steps To Reproduce

1. Finish autumn season
2. Get ready for next season
3. Boat arrives, winter season ends, I get rewards

### Playtest Version (center top)

v4.4.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Correct, need to implement an end of demo before winter

**Comment by Memori-Studios** [comment]
Added in 5.2.0
