### ISSUE TITLE
Typo in 'permenantly' in upgrade cards

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#45]
### Current Behavior

Typo in 'permenantly' in upgrade cards

### Expected Behavior

permenantly -> permanently

### Steps To Reproduce

Any upgade cards that have permanent effects.

### Playtest Version (center top)

v5.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 5.2.0 Thank you sir
