### ISSUE TITLE
Typo in 'Penentration' in upgrade cards

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#46]
### Current Behavior

Typo in 'Penentration' in upgrade cards

### Expected Behavior

Penentration -> Penetration

### Steps To Reproduce

Upgrade cards with Bodkin Bolts title

### Playtest Version (center top)

v5.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 5.2.0 metaprogression card clean up
