### ISSUE TITLE
no cancel buton on the upgrade menu

### ISSUE THREAD

**Issue by oerwoud2** [Memori-Studios/CastlesOnClouds-Playtest#47]
### Current Behavior

When you've done all the upgrades you can't continue because when you levelup you got to pick an upgrade but there are none to pick so you get stuck.

### Expected Behavior

Maybe add a cancel buton.

### Steps To Reproduce

play the game without any research unlocked until you run out of upgrades.

### Playtest Version (center top)

v5.1.0

### Seed (copy button center top)

Seed: 111013-9830

### Environment Specs

idk

**Comment by Memori-Studios** [comment]
Was this in regards to the upgrade Cards that pop up? If so this is resolved in 5.2.0 with a new back button
