### ISSUE TITLE
[Bug] Castle hitbox too big

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#5]
**Current Behavior**
Depending on the generation, enemies trigger health loss slightly further away from the actual location. Video included, pay attention to top left road

**Expected Behavior**
Damage on the castle touch instead of the road leading up to the castle

Playtest 3.4.4

**PC specs**
Gotta ask Kruse

**Anything else?**
Video below
[![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/02e7b40c-45f0-42f2-8901-e751a9c5beba)](https://clips.twitch.tv/SoftBlueWaspCoolStoryBro-T9nKUxE2EMaynIKJ)

**Comment by Memori-Studios** [comment]
Fixed in 4.2.1, idk why the sphere cast was set to 5 meters away, but it was
