### ISSUE TITLE
Constructing Building Overlaps with reroll/return on picking an advancement

### ISSUE THREAD

**Issue by Shatjo** [Memori-Studios/CastlesOnClouds-Playtest#52]
### Current Behavior

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/147779771/a2603e6c-584f-4901-b395-771c98142fec)

Constructing buildings overlaps with picking an advancement

### Expected Behavior

Disable Constructing Buildings overlay

### Steps To Reproduce

Play game
get exp
before you can pick a card click on construct buildings

### Playtest Version (center top)

6.0.0

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
resolved in 6.0.1, thanks
