### ISSUE TITLE
Camera movement isn't normalized

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#54]
### Current Behavior

So this is just my hunch but I believe that the camera movement isn't normalized in all directions. For example, it seems like that the speed is same for single button press but when I press any combination {W, A}, {W, D}, {S, A} or {S, D} the speed is little bit higher.

### Expected Behavior

Same speed in all 8 directions.

### Steps To Reproduce

Press any two combination of WASD

### Playtest Version (center top)

v6.0.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
youre the best man, resolved in 6.1.0
