### ISSUE TITLE
Merchant UI broken

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#55]
### Current Behavior

Shop UI not opening as expected

### Expected Behavior

Shop background and UI opens

### Steps To Reproduce

Wait til the merchant appears and click on the shop

### Playtest Version (center top)

v6.1.0

### Seed (copy button center top)

211012-8098

### Environment Specs

- OS: Windows 10
- GPU: RX 7700 XT
- CPU: I7 10700F
- RAM: 32 GBtyes

### Anything else?

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/5d92ef04-5789-4e56-b1b8-1ab4dbee039b)

**Comment by Micovec** [comment]
This is odd. I encountered this in 6.0.0 and 6.0.1 but not in 6.1.0. I did reset all game data in new version tho. Could you try that aswell and see if the issue persist?

**Comment by InsomniacSnorlax** [comment]
Just as you said. Resetting the game data fixes the issue
