### ISSUE TITLE
Selecting spells dissapear when you return to the main menu

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#57]
### Current Behavior

When I return to map generation menu all spells disappear and I get NullReferenceExceptions. I am still able to select them.

### Expected Behavior

No error messages and visible spells.

### Steps To Reproduce

- Open map generation
- Go back to main menu
- Open map generation again, spells dissapear

### Playtest Version (center top)

v6.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

### Anything else?

Also when I return to main menu selected spell icons remain visible at the bottom of the screen. I believe this is related so I won't create new bug report.

**Comment by Memori-Studios** [comment]
Fixed issue with spells disappear and I get NullReferenceExceptions, als0  selected spell icons remain visible at the bottom of the screen also resolved in 6.1.2
