### ISSUE TITLE
Replace 'asdfasdf' from seed

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#58]
### Description

This is not a big deal but in the full game it'll be more optimal to have something like 'N/A' in the seed instead of 'asdfasdf'. It is visible when starting the game.

**Comment by InsomniacSnorlax** [comment]
Lol you saw that too ay

**Comment by Memori-Studios** [comment]
haha yeah it was unprofessional but I am unprofessional, fixed
