### ISSUE TITLE
Discounts increase tower prices

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#59]
### Current Behavior

Increases tower costs and doesn't increase or decrease power ups

### Expected Behavior

Discounts applied properly

### Steps To Reproduce

OS: Windows 10
GPU: RX 7700 XT
CPU: I7 10700F
RAM: 32 GBtyes

### Playtest Version (center top)

v6.1.0

### Seed (copy button center top)

111012-7736

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Anything else?

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/0a3c34ef-cc88-4c08-9093-2d682c369859)
![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/793b91e1-7eb5-41af-9f5f-f158f674c153)

**Comment by Memori-Studios** [comment]
6.1.2 Might over magic card specifically corrected, costs now reduced and spells cooldowns are now shown in stats panel to display increased cooldown rate.
