### ISSUE TITLE
Card information improvements

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#60]
### Description

I have few ideas for card information improvements. They are just for better clarity and maybe it's my personal take.

### Highlight card effects more

I'd like to see more clearly which statistics will get enhanced and which won't, as it is with card levels (they have yellow color). I've highlighted them with green (positive effect) and red (negative effect) colors. Maybe apply yellow color for improved stats and red for worsened.

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/b20f18f6-6ce7-4b34-b568-6704f712a7f1)

### More information about percentages

At first glance at the card it is unclear which effect has 0% > 10% and which 0% > -3%. Maybe more information would be beneficial, something like:

Range: 0% > 10 %
Tax: 0% > -3%

instead of two round brackets: (0% > 10%) (0% > -3%).

### Some statistics don't make much sense

Some changed stats don't make sense. For example health:

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/1963073e-5f29-4e5c-9aad-af17843bab94)

This to me seems like I have 0 castle health and will have it at -2. I think they should be replaced with actual real numbers, my current health and changed health.

### Replace `>` with `->`

`>` character is used for comparison. I was a bit confused why there's card condition at the bottom but then after reading the description realized that it's just information about statistics. If you decide to change this maybe even for another improvement use a font that merges those two characters into one or modify the one you're using. What I mean is this:

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/c4b4ac29-c029-47b7-9a42-b2e2cfaf0cc1)

As you can see they are rendered as one character without any empty pixels between them. This is JetBrains mono font. If you're not sure how to change font manually maybe I can help with that or even do that for you.

**Comment by Memori-Studios** [comment]
![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/98005357/b502059d-ab25-4744-b6d8-0dc261dbf248)
Looking infinitely better, thanks man
