### ISSUE TITLE
Add options to view statistics when selecting a card

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#61]
### Description

It would be handy to have an option to view my current statistics when I'm selecting new card.

Maybe I have a stat improved so much I don't need to improve it more or a card will have a really negative impact on my stats but I won't know the final result of selecting such card until I actually do it.

Edit:
Resources aswell. Some cards give gold, change health etc.

**Comment by Memori-Studios** [comment]
implemented with other new card enhancements in 6.1.2
