### ISSUE TITLE
Formatted rolling text has visible functions for formatting

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#62]
### Current Behavior

I can't remember in which help popups this happens to but those who have formatted text in it (such as bold text) render rolling text character by character including format functions. I can see what function with what parameters are being called for a split of a second before they get actually formatted.

### Expected Behavior

Render rolling text in formatted version not in raw one.

### Steps To Reproduce

Get a help popup that has formatted text. I _think_ bleed popup has it but I'm not sure.

### Playtest Version (center top)

v6.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Fixed in 6.1.2, been meaning to do this forever now its much better thanks
