### ISSUE TITLE
Game speed has effect on camera movement

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#63]
### Current Behavior

When I pause the game with pause button camera movement slows down and also speeds up on fast forward. This happens for WASD and for mouse camera movement.

### Expected Behavior

Have same camera speed independent on game speed.

### Steps To Reproduce

- Pause or fast forward game

### Playtest Version (center top)

v6.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
is a weird issue with physics due to the rigidbody targets. Implemented a bandaid fix in 6.0.2
