### ISSUE TITLE
Player units vanish when placed far from enemies

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#64]
### Current Behavior

Units that are placed far from enemies vanish after few seconds. I actually like being able to place them on grass so they attack from sides but when they are too far they vanish.

### Expected Behavior

I should be able to place units just far enough away to be able to attack enemies.

### Steps To Reproduce

- Take spell that places units
- Place unit on the opposite side of the map for example, they vanish after few seconds

### Playtest Version (center top)

v6.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
I am pretty sure this is just a rendering/culling issue with the grass shader on linux. Cannot reproduce. from my testing they are there for the full amount of time then disappear.  can you confirm this happening?

**Comment by Micovec** [comment]
I'm not able to reproduce it either now. I can't remember at what conditions it had happened. I'll close this and reopen if i encounter it again.
