### ISSUE TITLE
Picking card on multiple card draws decrements reroll count

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#65]
### Current Behavior

Reroll decrements on its own when I pick a card on two or more draw cards.

### Expected Behavior

No reroll decrementing.

### Steps To Reproduce

- Wait until you have two or more draw cards
- Draw a card, reroll decrements

### Playtest Version (center top)

v6.1.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Thanks, fixed in 6.1.2
