### ISSUE TITLE
Units don't check for invalid placement location

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#68]
### Current Behavior

Units can be placed on water, inside hills, on mine and inside castle.

### Expected Behavior

I should not be able to place units in locations mentioned above.

### Steps To Reproduce

- Take spell that spawns any unit
- Place unit on any of locations mentioned above

### Playtest Version (center top)

v6.0.1

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
not worth fixing atm, if someone wants to place it in a weird spot they can send it
