### ISSUE TITLE
Advacement menu interaction

### ISSUE THREAD

**Issue by colelli** [Memori-Studios/CastlesOnClouds-Playtest#69]
### Current Behavior

When a new advancement is reached the player can choose one of the shown cards. While in this state if you press the "Esc" key, it will bring you to the pause menu and two bugs will happen:
1. The advancement icons and effects are still visible and interacting with the cursor
2. If the user clicks on one of them to choose an advancement the game will resume while on pause

A preview can be seen in the image below:

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/153321251/e8cd2050-a566-4069-85d2-0678a0bd60d1)

### Expected Behavior

1. The advancement market disappears
2. There is no way for the player to interact with the market and bring the game in any unwanted "mixed" state (paused but playing).

### Steps To Reproduce

1. Reach an advancement
2. Press "Esc"
3. Select any of the advancements

### Playtest Version (center top)

v6.1.2

### Environment Specs

- OS: Windows 11 Home
- GPU: Nvidia GTX 1650Ti
- CPU: i5-10300H
- RAM: 8 GB

**Comment by Memori-Studios** [comment]
Fixed in next build. Escape now returns you to game if card draw panel is open. Thanks
