### ISSUE TITLE
[Bug] Upgrades reset after playing game

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#7]
**Current Behavior**
After upgrading, if the player completes a game the upgrades will revert to its previous state

**Expected Behavior**
Retain upgrades

**Steps To Reproduce**
1. Select Upgrades
2. Play game
3. Surrender/Lose etc
4. Check Upgrades

Playtest 3.4.4

**Anything else?**
Upgrades can be saved if right after upgrading, close and restart the game

**Comment by Memori-Studios** [comment]
Fixed in Playtest 4.1.1

Error was due to cloudstone relic application on game end overwriting save data
