### ISSUE TITLE
View all tips!

### ISSUE THREAD

**Issue by BinglingBingus** [Memori-Studios/CastlesOnClouds-Playtest#70]
### Description

Just find it a little difficult to understand certain things, saw a poison pop-up and thought wait what did it do again?
OR wtf do farms do exactly, gold per turn? what's a turn. a wave?

Very fun little game, quite punishing to begin with, but unsure if it's just the different style of TD roguelike that does me in.
thought I was cracked at TD

**Comment by Memori-Studios** [comment]
Added comments to the pop ups and enemies to show you how you can see the info in the encyclopedia.  Also cleaned up the econ so it makes more sense. Thanks for the feedback, it really helps me know what new users think!
