### ISSUE TITLE
Celestial college of convergence has overflowing text

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#71]
### Current Behavior

Celestial college of convergence has overflowing name on structure selection

### Expected Behavior

No overflow

### Steps To Reproduce

1. Open MilitaryAcademy build menu

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 6.4.0, also cleaned up a good bit of the formatting
