### ISSUE TITLE
How to menus are outdated

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#72]
### Current Behavior

When there's How-To menu its description is outdated. This involves almost all of menus.

### Expected Behavior

Menus should have the latest description.

### Steps To Reproduce

1. Reset all game data
2. Play the game, wait for How-To menu

### Playtest Version (center top)

v6.2.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Finally got around to redoing all of them in 7.2.3 with the new ui and heroes added. Thanks!
