### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#73]
### Current Behavior

Apart from main menu the translations are missing everywhere else.

### Expected Behavior

All text translated.

### Steps To Reproduce

1. Switch to different language than English
2. Go to any other part of the game except main menu, there are missing translations

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
not a bug, game is in active development and I am still working on translations
