### ISSUE TITLE
Pick 'em clean gives 10% instead of advertised 3%

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#76]
### Current Behavior

Pick 'em clean card gives 10% instead of advertised 3%

### Expected Behavior

Pick 'em clean card should give advertised 3%

### Steps To Reproduce

1. Wait for first Pick 'em clean card
2. Take a look at stats, gold drop rate is at 110% instead of 103%

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved
