### ISSUE TITLE
Enemy info menu makes stat menu scrollable with WS keys

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#77]
### Current Behavior

Stat menu is scrollable with WS keys after opening enemy info menu.

### Expected Behavior

Stat menu should not be scrollable with WS keys.

### Steps To Reproduce

1. Open stat menu
2. Wait for enemy info
3. Click on enemy info icon
4. Close enemy info menu
5. Press WS several times, stat menu scrolls

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 6.4.0
