### ISSUE TITLE
Error on first merchant

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#78]
### Current Behavior

I get this error when I open merchant for the first time 

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/11058026-58fa-4256-a5bf-46cd98af85fc)

### Expected Behavior

No error.

### Steps To Reproduce

1. Wait for the first merchant
2. Open the menu

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
cant reproduce, would need to see the log files

**Comment by Micovec** [comment]
Just to add:

I reset all game data and then the error happened on first merchant. There were no errors after that.

[Player.log](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/files/14812071/Player.log)

**Comment by Memori-Studios** [comment]
interesting, might be because you are on linux. I tried this, will ask you to test when next build is uploaded 
https://www.reddit.com/r/Unity3D/comments/uz6x25/windowsvideomedia_error_unhandled_color_standard_0/

**Comment by Memori-Studios** [comment]
No longer appearing, if it pops up again reopen this
