### ISSUE TITLE
[Bug] Missing magic missile III

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#8]
**Current Behavior**
Missing magic missile 3 hence can't upgrade to final stages

**Expected Behavior**
Upgrade beyond missile 2

**Steps To Reproduce**
1. Upgrade magic tower
2. Reach magic missle 2

Playtest 3.4.4

**Anything else?**
![image](https://cdn.discordapp.com/attachments/1006071199559843863/1191017736738963456/image.png?ex=65a3e8b4&is=659173b4&hm=3fe62b836829f1a619f69833716942e55592584a87f6dffb71458b2e79643ec5&)

**Comment by Memori-Studios** [comment]
Fixed in 4.1.1
