### ISSUE TITLE
Merchant's prices overflow

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#80]
### Current Behavior

When the prices of merchant's items are too high they overflow:

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/f1dcf04a-0a36-4b34-9397-225d286aec76)

### Expected Behavior

No overflow for item's price

### Steps To Reproduce

1. Have very large amount of gold, not sure on this one

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 6.4.0
