### ISSUE TITLE
Relics to the right of structure selecting menu have odd animation

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#81]
### Current Behavior

It seems like relics that are to the right of structure selecting menu (those that were purchased from merchant) don't have animation by their own, only if I hove mouse over them and then the animation is somewhat borked.

### Expected Behavior

Either show animation or don't.

### Steps To Reproduce

1. Buy relic from merchant
2. Repeatedly hover mouse over the relic, the animation is somewhat borked

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
Had some over complicated logic to make them only spin when moussing over and to reset afterwards, but after reading this I just changed it to make them spin at all times which looks less goofy

**Comment by Micovec** [comment]
I thought that might be the case. You could also keep them spin when hovering over but keep the time they spent in animation meaning they would resume the animation.
