### ISSUE TITLE
I can buy the same relic multiple times

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#82]
### Current Behavior

I am able to buy the same relic multiple times result in other bugs such as having so many cards in card draw that some cards aren't visible anymore.

### Expected Behavior

I should not be able to buy the same relic more than once.

### Steps To Reproduce

1. Buy relic from merchant
2. Be lucky and get it for the second time, you will be able to buy it

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 6.4.0, thanks as always
