### ISSUE TITLE
Tower's visible radius doesn't get changed on upgade

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#83]
### Current Behavior

When I buy an upgrade for a tower the visible range doesn't get updated. It is only after I reselect the tower that the range is the correct size.

### Expected Behavior

Update range tower on upgrade.

### Steps To Reproduce

1. Upgrade tower, the range (in white) doesn't get updated

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 6.4.0
