### ISSUE TITLE
Pressing escape in in-game encyclopedia doesn't close it

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#84]
### Current Behavior

When I press escape with encyclopedia open in-game it doesn't close it instead it closes the escape menu leaving the game running with encyclopedia on top.

### Expected Behavior

Pressing escape with encyclopedia open in-game should close the encyclopedia leaving escape menu opened.

### Steps To Reproduce

1. Run the game
2. Open menu
3. Open encyclopedia
4. Press escape, encyclopedia remains open but menu closes

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved in 6.4.0
