### ISSUE TITLE
Can buy cards that lower castle health to 0

### ISSUE THREAD

**Issue by Micovec** [Memori-Studios/CastlesOnClouds-Playtest#85]
### Current Behavior

I can buy cards that lower castle health to 0 or below zero, such as quantitative easing.

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/30734146/92cb6010-a0c4-4c3f-889d-5789b5386a46)

### Expected Behavior

I should not be able to buy cards that lower castle health to zero or negative health.

### Steps To Reproduce

1. Buy card such as quantitative easing multiple times

### Playtest Version (center top)

v6.3.0

### Environment Specs

- OS: Arch Linux
- GPU: Nvidia RTX 3070
- CPU: Ryzen 5600X
- RAM: 32 GB

**Comment by Memori-Studios** [comment]
resolved, thanks
