### ISSUE TITLE
Save and Continue Does Not Work

### ISSUE THREAD

**Issue by zachrussell12** [Memori-Studios/CastlesOnClouds-Playtest#86]
### Current Behavior

Finished all 9 waves of a season. A menu popped up and asked if I wanted to "Continue" or "Save and Quit." I clicked save and quit only to realize it did not same my game. I tried closing the game to maybe let Steam sync the game data however the save still wasn't there.

### Expected Behavior

It should actually save the run where its at and allow me to resume when I want.

### Steps To Reproduce

Go through all 9 waves of a season, reach the menu with the options, click "Save and Quit." Observe it not being there when clicking Start Game. The only option available is "New Game."

### Playtest Version (center top)

v6.3.0

### Seed (copy button center top)

111012-7942

### Environment Specs

- OS: Windows 10
- GPU: Nvidia GeForce RTX 3070
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- RAM: 128 GB

**Comment by Memori-Studios** [comment]
Fixed in 7.0.2, thanks!
