### ISSUE TITLE
Game Crashes when resetting All Game Data

### ISSUE THREAD

**Issue by zombiehunternr1** [Memori-Studios/CastlesOnClouds-Playtest#87]
### Current Behavior

When you press the "Reset all Game Data" the game crashes.

### Expected Behavior

It should probably come up with a prompt asking to confirm if you wanna reset all game data, and once you do it resets it without crashing.

### Steps To Reproduce

Start the game, go to settings, and press the button.

### Playtest Version (center top)

v6.3.0

### Seed (copy button center top)

111012-2477

### Environment Specs

- OS: [eg. Windows 10 64-bit]
- GPU: [eg. Nvidia RTX 3070]
- CPU: [eg. i5-14600KF]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
No longer in settings, reset game data does bring up a prompt now
