### ISSUE TITLE
UI scaling in Upgrade menu small/Offset

### ISSUE THREAD

**Issue by zombiehunternr1** [Memori-Studios/CastlesOnClouds-Playtest#88]
### Description

The UI layout in the upgrade menu looks very small and offset. I've put in a screenshot to show what I ment along with the settings I'm currently running the game in if that helps.

![Progression UI layout](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/44666850/1cf89d75-0ae9-4b4b-930b-1ad95c636214)

**Comment by Memori-Studios** [comment]
Fixed in 7.0.2, now properly scales on 4k and ultrawide. Also totally redid the ui for the metaprogression menu, should look much better now
