### ISSUE TITLE
Spell loadout selection issue

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#91]
### Current Behavior

Hovering over spell slot has the selection screen somewhat transparent

### Expected Behavior

Selection screen for spell loadouts should be solid over the current spell slots

### Steps To Reproduce

1. Hover over spell loadouts in New Game
2. Generate Island on Epic (Not sure if the others trigger it)
3. Unfocus the game
4. Refocus and Generate another island
5. Might need a few retries to achieve the issue

### Playtest Version (center top)

V7.1.1

### Seed (copy button center top)

Seed: 211012-3233

### Environment Specs

- OS: Windows 10
- GPU: RX 7700
- CPU: i7-10700F
- RAM: 32 GB

### Anything else?

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/e6b6bc85-f7ba-45e7-999e-c3dd332492d3)

**Comment by Memori-Studios** [comment]
What resolution? Im unable to recreate

**Comment by InsomniacSnorlax** [comment]
On relaunch today the issue does not appear. Could be due to old data still being on my system

**Comment by Memori-Studios** [comment]
Can you reset all game data and see if it occurs? I cannot for the life of me reproduce it

**Comment by Memori-Studios** [comment]
Fixed in 7.2.2, completely redid the panel, much better now thanks
