### ISSUE TITLE
Weird texturuing

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#93]
### Current Behavior

blackish texture under the grass

### Expected Behavior

No blackish texture

### Steps To Reproduce

Autumn, Year 1 Seed: 111012-96011s

### Playtest Version (center top)

V7.2.0

### Seed (copy button center top)

Seed: 111012-96011

### Environment Specs

- OS: Windows 10
- GPU: RX 7700
- CPU: i7-10700F
- RAM: 32 GB

### Anything else?

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/8166664e-e0ec-4297-836e-ea4372ceac76)
![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/d2eb6739-0535-4e90-a50f-403cd2aba4af)

**Comment by Memori-Studios** [comment]
Fixed in 7.2.1, was marks from artillery towers from past seasons
