### ISSUE TITLE
Support buildings

### ISSUE THREAD

**Issue by InsomniacSnorlax** [Memori-Studios/CastlesOnClouds-Playtest#94]
### Current Behavior

In the **second season**, you can build **artillery towers** without the **Forge Cannon Institute** as it was placed in the prior season while placing a **Mystic Collegium** doesn't allow for **Magic Towers** to be constructed.

### Expected Behavior

- Need to build **Forge Cannon Institute** again to construct **Artillery Towers**
- Building **Mystic Collegium** in other seasons allows the construction of **Magic Towers**

### Steps To Reproduce

1. Place Forge Cannon Institute in season 1
2. Proceed to season 2
3. Place town Artillery tower
4. Place Mystic Collegiunm
5. Attempt to place magic tower

### Playtest Version (center top)

V7.2.0

### Seed (copy button center top)

Seed: 111012-96011

### Environment Specs

- OS: Windows 10
- GPU: RX 7700
- CPU: i7-10700F
- RAM: 32 GB

### Anything else?

![image](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/94978222/4e289233-2994-4240-a967-75778c4c7d4e)

**Comment by Memori-Studios** [comment]
fixed in 7.2.1, was due to changing some card ids for ordering purposes. You will now have to rebuild both of them
