### ISSUE TITLE
Rotating Right Key bind not updated after change

### ISSUE THREAD

**Issue by Swalscha** [Memori-Studios/CastlesOnClouds-Playtest#95]
### Current Behavior

Clicking on the "Rotating Right" key bind button, after pressing any key, there is no update of the chosen key.

### Expected Behavior

Update of the key bind to confirm it.

### Steps To Reproduce

See before.

### Playtest Version (center top)

Demo 7.3.0

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

### Anything else?

Not sure the performance settings really change either: the selected options are visible but they don't seem to apply (going to low performance in the setting doesn't make any difference in my CPU-GPU usage and the settings aren't saved from one play to the next one).

**Comment by Memori-Studios** [comment]
Checked the rotating camera, it works fine for me. I should clarify that it is for the ingame camera, not the menu. 

Uploading 2024-07-30 11-11-10.mp4…

**Comment by Memori-Studios** [comment]
Tested resetting the keys and rotating camera, along with changing the settings, are you seeing something different?

https://github.com/user-attachments/assets/79f37c22-a920-4965-812a-6422500f4e89
