### ISSUE TITLE
Unlock feature ain`t working

### ISSUE THREAD

**Issue by Bafffe** [Memori-Studios/CastlesOnClouds-Playtest#96]
### Current Behavior

Unlocking different buildings like lumbermill or getting upgrades like mortar slowing will be unlocked but not applied, so you still dont have the lumbermill in battle or the slowing mortar (examples)

### Expected Behavior

Well, the unlocked items either should be possible to purchase in the metaprogression or ingame or just be applied

### Steps To Reproduce

just unlock smth in the unlock tab ingame and you should see that you completed smth but still dont have it (For example try unlocking the lumbermill and then try to place it in a game)

### Playtest Version (center top)

v0.0.2

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
Thank you for posting. I have fixed this in 0.0.3 so unlocks will now grant building access. Mortars should be working but maybe the speed decrease is too small to see. Will investigate more and fix if needed. If the issue persists feel free to @ me on Discord 

https://store.steampowered.com/news/app/1668620/view/4261054972288595915
