### ISSUE TITLE
Can't exit metaprogression if in fullscreen

### ISSUE THREAD

**Issue by Panner-zz** [Memori-Studios/CastlesOnClouds-Playtest#97]
### Current Behavior

when I'm in fullscreen the resolution of my monitor isn't big enough so the exit button is off the edge of the screen, making it impossible to exit the metaprogression window (basically softlocking me). 

### Expected Behavior

UI should resize to the resolution of my screen

### Steps To Reproduce

quick fix, maybe some anchor points for the exit button. Otherwise great game!

### Playtest Version (center top)

v0.0.2

### Environment Specs

- OS: Windows 11
- GPU: Nvidia RTX 3080
- CPU: i9
- RAM: 64

**Comment by Memori-Studios** [comment]
Fixed in 0.0.3. Hey man, can you let me know what resolution your screen is so I can double check that I corrected it? It works on 1080, 720, Ultrawide, and free aspect now, but Ill make sure its fixed for yours.

https://store.steampowered.com/news/app/1668620/view/4261054972288595915

**Comment by Panner-zz** [comment]
I'm working with 1920 1080 and it works fine now, thanks for the quick fix!
